feat: support key prefixes, parse action arguments, add more tests
bezhermoso/tree-sitter-ghostty pull request #1
Opened 2024-12-28 07:37 UTC by gerblesh

Hi! Awesome work on this repo! This PR adds support for key prefixes, detailed here: https://ghostty.org/docs/config/reference#keybind
something like:
`keybind = ctrl+physical:a=close_window`
This should also fix parsing the individual arguments for actions:
`keybind = ctrl+physical:a=resize_split:right,10`
would parse the `right`, the `,` and the `10` individually rather than as `raw_value`

2024-12-28 19:27 UTC, gerblesh commented
It seems like `raw_value` is not needed as a fallback anymore, is it worth removing?

2024-12-28 21:01 UTC, bezhermoso requested changes
Thank you for contributing! 

Good work here, can you please rebase with latest main as I've made some progress since? I've also added a test corpus, so if you can add test cases for these that would be lovely (I'm working on GitHub Actions in a bit)

2024-12-28 21:27 UTC, gerblesh commented
thanks for the review, implemented the suggested changes, and added back the string literal. Lmk if/how you want to remove the string literal

2024-12-28 21:28 UTC, gerblesh commented on grammar.js
> +          field("argument", alias($._arg_list, $.action_argument)),
Sounds good, didn't know that!

2024-12-28 21:46 UTC, gerblesh commented
https://github.com/ghostty-org/ghostty/blob/main/src/input/key.zig#L255
is where all of the special keys live, is it best to put these in the grammar or just regex match?

2024-12-28 22:17 UTC, bezhermoso commented
@gerblesh As to `raw_value`, its there just as a catch-all. However it's a bit too greedy because of how tree-sitter decides lexical precedence, so I don't love it but its the only way to handle Ghostty's optional quotes around strings. 

I think this is solvable w/ the right tree-sitter grammar knowledge, but let's keep this PR scoped down to fleshing out the keybinding grammar for now.

2024-12-28 22:21 UTC, gerblesh commented
Ok squashed everything, should be ready for another look over

2024-12-29 00:26 UTC, bezhermoso requested changes
Few more suggestions. Thanks for spending time on this. 🙏

2024-12-29 00:26 UTC, bezhermoso commented on grammar.js
> +
I think it makes a bit more sense for the `seq(..., token.immediate(":"))` here.

2024-12-29 00:26 UTC, bezhermoso commented on grammar.js
> +    ),
I'm not sure snake-case is appropriate here e.g. Ghostty allows some Unicode chars here like `ö`. 

Can we bring the permissive regex back and deal with handling the right characters in another PR?

2024-12-29 01:31 UTC, gerblesh commented on grammar.js
> +    ),
would it make sense to have a `choice()` between the identifier and the permissive regex here?

2024-12-29 01:42 UTC, gerblesh commented on grammar.js
>      // Expressed as separate regexes to avoid lexical precedence issues with `raw_value`
whoops, the `prec` is no longer needed. The string literal was added back for handling quoted values in the keybind directive

2024-12-29 02:40 UTC, bezhermoso commented on grammar.js
> +    ),
I don't think that makes sense because the permissive regex would be inclusive of the identifier, where both aren't even named nodes in the syntax tree.

2024-12-29 02:43 UTC, bezhermoso commented on grammar.js
> +    _keybind_value: $ => choice($.keybind_value, alias("clear", $.value), alias($.string_literal, $.value)),
```suggestion
    _keybind_value: $ => choice($.keybind_value, alias("clear", $.keybind_clear_keyword), alias($.string_literal, $.value)),
```

could be helpful to query for (e.g. capture as a highlight group)

2024-12-29 04:03 UTC, bezhermoso commented on grammar.js
> +    ),
Actually yeah this works better!

2024-12-29 04:04 UTC, bezhermoso commented on grammar.js
> +    _snake_case_identifier : $ => /[a-z\_]+\d*/,
I'll fix this post-merge. Thanks!

2024-12-29 04:05 UTC, bezhermoso approved these changes

2024-12-29 04:05 UTC, merged