fix: regex tweaks, generalize directives
bezhermoso/tree-sitter-ghostty pull request #4
Opened 2024-12-29 22:53 UTC by gerblesh

This fixes an issue with the keybind directive not having the proper "=" token, by making the `key` regex ignore whitespace. It also generalizes the directives into a function and replaces `0-9` with `\d` for numbers in regex. This should fix issues with the syntax highlighting for the `=` sign with the `keybind` directive as well.

2024-12-29 23:55 UTC, bezhermoso requested changes

2024-12-29 23:55 UTC, bezhermoso commented on grammar.js
> +const number = /[\d]+(\.[\d]+)?/;
I really don't think this is an improvement. We know we only want `[0-9]` and not any Unicode digits that could match. Unless paired with `/d` pattern modifier to intentionally match a broader set of digit characters, this doesn't achieve anything but slightly obfuscate.

2024-12-29 23:55 UTC, bezhermoso commented on grammar.js
> +        field("bind", choice(/[a-z\d]+(\_[a-z\d]+)*/, /[^>=:\s]{1}/)),
Please undo the change from `[0-9]`.

2024-12-29 23:55 UTC, bezhermoso commented on grammar.js
> +      ),
`value` is not optional for `config-file` and `keybind`.

2024-12-30 00:16 UTC, gerblesh commented on grammar.js
> +      ),
Just tested, it definitely is, whether or not it is intentional, I don't know

2024-12-30 00:20 UTC, gerblesh commented on grammar.js
> +const number = /[\d]+(\.[\d]+)?/;
Sounds good. Saw other TS grammars using it so figured it was 'best practice.' Though looking more closely we likely don't want to be matching unicode digits

2024-12-30 00:31 UTC, gerblesh commented on grammar.js
> +      ),
yeah, `keybind = ` seems to be analogous to `keybind = clear`, and `config file =` clears out the includes. 
The config format says here in https://ghostty.org/docs/config
```ini
# Empty values reset the configuration to the default value
font-family =
```
So it seems like it's intentional

2024-12-30 00:39 UTC, bezhermoso commented on grammar.js
> +      ),
Ahh. Sounds good 👍

2024-12-30 01:01 UTC, gerblesh commented
Squashed everything. Should be ready for merging unless there's something that needs changing/fixing

2024-12-30 01:05 UTC, bezhermoso commented on grammar.js
> +    _snake_case_identifier : $ => /[a-z\_]+[0-9]*/,
This can be addressed in another PR

2024-12-30 01:05 UTC, bezhermoso approved these changes

2024-12-30 01:05 UTC, bezhermoso commented
Thank you!

2024-12-30 01:05 UTC, merged

2024-12-30 01:25 UTC, bezhermoso commented on grammar.js
> +    _snake_case_identifier : $ => /[a-z\_]+[0-9]*/,
Now that I think about it, it's because it's an unanchored pattern. Which should be fine.